favicon: /favicon.png
open_graph:
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

logo: 
  text: BCMDR

article:
  readtime: false

menu:
  All Posts: /archives
  Articles: /categories/Articles
  Tutorials: /categories/Tutorials
  Sessions: /categories/Sessions
  # About: /about

search:
  type: insight

# share:
#   type: sharethis
#   install_url:

# comment:
#   type: discus
#   shortname:

plugins:
  mathjax: false
  gallery: true
  google-analytics:
    tracking_id:

navbar_links:
  GitHub:
    icon: fab fa-github
    url: https://github.com/bcmdr

footer_links:
  GitHub: https://github.com/bcmdr/hexo-site
